#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : urllib3
Version  : 1.10.4
Release  : 18
URL      : https://pypi.python.org/packages/source/u/urllib3/urllib3-1.10.4.tar.gz
Source0  : https://pypi.python.org/packages/source/u/urllib3/urllib3-1.10.4.tar.gz
Summary  : HTTP library with thread-safe connection pooling, file post, and more.
Group    : Development/Tools
License  : MIT
Requires: urllib3-python
BuildRequires : backports.ssl_match_hostname
BuildRequires : certifi-python
BuildRequires : cffi-python
BuildRequires : cryptography-python
BuildRequires : mock-python
BuildRequires : ndg_httpsclient-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pyOpenSSL-python
BuildRequires : pyasn1-python
BuildRequires : pycparser-python
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six-python
BuildRequires : tornado-python

%description
# Building the Docs
First install Sphinx:
pip install sphinx
Install pyopenssl and certifi dependencies, to avoid some build errors. (Optional)

%package python
Summary: python components for the urllib3 package.
Group: Default

%description python
python components for the urllib3 package.


%prep
%setup -q -n urllib3-1.10.4

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
